name: bunny_sdk_player_ff
description: Bunny Stream native Android player for Flutter (Maven Central)
version: 0.0.4
homepage: https://github.com/krishnatsn/bunny_sdk_player_ff
repository: https://github.com/krishnatsn/bunny_sdk_player_ff

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_bunny_video_player
        pluginClass: FlutterBunnyVideoPlayerPlugin
